### ISSUE TITLE
Uncaught TypeError: err.match is not a function in packages/diagrams/lib/diagrams.js:151

### ISSUE THREAD

**Issue by chrissto79** [francoislaberge/atom-diagrams#2] opened 2016-11-26 10:38 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.5
**Electron Version**: 1.3.9
**System**: Mac OS X 10.12.1
**Thrown From**: [diagrams](https://github.com/francoislaberge/atom-diagrams) package, v0.23.4

### Stack Trace

Uncaught TypeError: err.match is not a function

```
At /Users/.../.atom/packages/diagrams/lib/diagrams.js:151

TypeError: err.match is not a function
    at process.nextTick.err (/Users/.../.atom/packages/diagrams/lib/diagrams.js:151:49)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -8:41.6.0 editor:indent (atom-text-editor.editor.is-focused)
     -8:38.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:15.4.0 settings-view:open (atom-text-editor.editor.is-focused)
     -8:05.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 11x -7:56.2.0 core:undo (atom-text-editor.editor.is-focused)
     -7:49.4.0 core:save (atom-text-editor.editor.is-focused)
 11x -7:48.4.0 core:undo (atom-text-editor.editor.is-focused)
     -7:43.1.0 core:save (atom-text-editor.editor.is-focused)
     -7:10.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:05.8.0 core:save (atom-text-editor.editor.is-focused)
     -6:38.8.0 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  4x -6:37.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:33 core:save (atom-text-editor.editor.is-focused)
     -4:30.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -4:29.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:08.5.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "terminal-panel",
      "language-dot"
    ],
    "projectHome": "/Users/.../Sites",
    "telemetryConsent": "no",
    "themes": [
      "one-light-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
diagrams, v0.23.4 (active)
git-control, v0.8.2 (inactive)
git-history, v3.2.0 (inactive)
git-line, v0.5.0 (inactive)
git-log, v0.4.1 (active)
git-plus, v5.25.5 (active)
git-time-machine, v1.5.4 (inactive)
language-docker, v1.1.7 (active)
language-dot, v1.6.0 (inactive)
markdown-mindmap, v0.2.4 (active)
markdown-pdf, v1.5.0 (inactive)
markdown-toc, v0.4.1 (inactive)
php-integrator-base, v1.2.6 (active)
php-integrator-linter, v1.2.1 (active)
platformio-ide-terminal, v2.2.2 (active)
pretty-json, v1.6.1 (active)
project-manager, v3.3.3 (active)
python-indent, v1.0.0 (active)
python-tools, v0.6.8 (active)
source-preview, v0.5.0 (inactive)
xml-formatter, v0.10.0 (inactive)
xml-tools, v0.2.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (active)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by seflless** [comment] 2016-12-28 06:39
@chrissto79 Do you have any repro steps for this?

**Comment by chrissto79** [comment] 2016-12-29 13:34
yes. I created a test.dot file with following graph definition:

```
digraph G {
    main -> parse -> execute;
    main -> init;
    main -> cleanup;
    execute -> make_string;
    execute -> printf
    init -> make_string;
    main -> printf;
    execute -> compare;
}

```

still getting errors after update to atom 1.12.7


Sequence files are working fine.

I tried it with the underlying diagrams node project and it's working like a charm also for dot files.

**Comment by seflless** [comment] 2017-01-02 19:17
Sorry for the slow responses. I'm on the longest vacation I've ever taken and it's great. 

Hmmmm. Looked a little deeper, looks like the underlying viz.js is using 'eval' calls that are now getting blocked by a security policy probably caused by an Electron/V8 runtime update in Atom.

**Comment by seflless** [comment] 2017-01-02 19:23
Looks like the Atom team may have provided a solution, looking into it:
https://github.com/atom/loophole

**Comment by seflless** [comment] 2017-01-03 06:04
Alright, this should be fixed in: https://github.com/francoislaberge/atom-diagrams/releases/tag/v0.26.0

**Closed as completed by seflless** 2017-01-03 06:04 UTC

**Comment by seflless** [comment] 2017-01-03 06:07
@chrissto79 Should be fixed now. I tested it out a bit from a fresh install too. Wrapping it in a webworker was the only option that worked, it seems to be faster now too, but maybe that's my imagination.

/cc @michaeloboyle @jagui
